# Generated by Django 2.2 on 2019-04-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
