# Generated by Django 2.2 on 2019-04-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_auto_20190405_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.TextField(max_length=1000),
        ),
    ]
