# Generated by Django 2.2 on 2019-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0003_auto_20190405_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.TextField(max_length=100),
        ),
    ]
