# Generated by Django 2.2 on 2019-04-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0004_auto_20190406_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='description',
        ),
        migrations.AddField(
            model_name='source',
            name='keyword',
            field=models.CharField(default='Cardano', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
